module.exports = {
  // actions
  "PING": 0x01,
  "PONG": 0x02,
  "SPAWN_PLAYER": 0x03,
  "ADD_PLAYER": 0x04,
  "UPDATE_PLAYERS": 0x05,
  "UPDATE_SPELLS": 0x06,
  "PLAYER_MOVE": 0x07,
  
  // cast
  "CAST_PRIMARY": 0x08,
  
  // types
  "SPELL_PRIMARY": 0x0A,
  
  // direction
  "DIRECTION_WEST": 0X14,
  "DIRECTION_EAST": 0X15,
  "DIRECTION_NORTH": 0X16,
  "DIRECTION_SOUTH": 0X17,
  "DIRECTION_NWEST": 0X18,
  "DIRECTION_NEAST": 0X19,
  "DIRECTION_SWEST": 0X1A,
  "DIRECTION_SEAST": 0X1B
};